language: android
jdk: oraclejdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2

android:
  components:
    - tools
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script: ./gradlew clean check test
